icarus:
  listen_address:     localhost
  listen_port:        61001
  security_token:     abcdefghijklmn1234567890
  username:           daedalus
  password:           sosecretpassword1234567890
  ssl_private_key:    private.key
  ssl_certificate:    server.crt
  backends:           [system, powerdns, postfix, proftpd]

postfix:
  prefix:      /home/virtual
  maildirmake: /usr/bin/maildirmake
  user:        virtual
  group:       virtual

proftpd:
  path:        '/home/hosting/:domain/web/:subdomain'